package workflow

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRunProviderCommandDispatch proves runProviderCommand — the single
// resolution+dispatch point shared by a live agent call and one-off text
// generation — routes to the right raw invocation for a given resolved
// provider name, with no special-casing at the call site.
func TestRunProviderCommandDispatch(t *testing.T) {
	clearProviderEnv(t)
	tmp := t.TempDir()

	fakeCodex := fakeCodexBinary(t, filepath.Join(tmp, "codex-argv.log"), `{"via":"codex"}`)
	setClaudeCLI(t, fakeClaudeBinary(t, `{"result":"via claude"}`))
	wrapperScript := filepath.Join(tmp, "fake-wrapper.sh")
	if err := os.WriteFile(wrapperScript, []byte(`#!/bin/sh
printf '{"via":"wrapper"}' > "$PALLIUM_WORKFLOW_OUTPUT_FILE"
`), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PALLIUM_WORKFLOW_PROVIDER_GROK_COMMAND", wrapperScript)

	agent := &Agent{Mode: "read-only", Prompt: "hello"}

	cases := []struct {
		name     string
		provider string
		want     string
	}{
		{name: "codex", provider: "codex", want: "codex"},
		{name: "configured wrapper wins for any non-codex name", provider: "grok", want: "wrapper"},
		{name: "claude built-in when no wrapper configured", provider: "claude", want: "via claude"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			callTmp := t.TempDir()
			outFile := filepath.Join(callTmp, "last-message.txt")
			usageFile := filepath.Join(callTmp, "usage.json")
			r := &Runner{CodexBinary: fakeCodex}
			out, err := r.runProviderCommand(context.Background(), tc.provider, callTmp, outFile, usageFile, callTmp, agent.Prompt, agent, AgentOptions{}, false)
			if err != nil {
				t.Fatalf("runProviderCommand(%q) error: %v", tc.provider, err)
			}
			if !strings.Contains(out, tc.want) {
				t.Fatalf("runProviderCommand(%q) = %q, want it to contain %q", tc.provider, out, tc.want)
			}
		})
	}
}

// TestRunProviderCommandUnconfiguredProviderErrors proves an unrecognized
// provider with no configured wrapper fails with a clear, actionable error
// instead of silently falling back to any built-in.
func TestRunProviderCommandUnconfiguredProviderErrors(t *testing.T) {
	clearProviderEnv(t)
	tmp := t.TempDir()
	agent := &Agent{Mode: "read-only", Prompt: "hello"}
	r := &Runner{}
	_, err := r.runProviderCommand(context.Background(), "gemini", tmp, filepath.Join(tmp, "out.txt"), filepath.Join(tmp, "usage.json"), tmp, agent.Prompt, agent, AgentOptions{}, false)
	if err == nil {
		t.Fatal("expected an error for an unconfigured provider")
	}
	if !strings.Contains(err.Error(), "PALLIUM_WORKFLOW_PROVIDER_GEMINI_COMMAND") {
		t.Fatalf("expected error to name the expected env var, got: %v", err)
	}
}

// TestRunProviderTextDispatchesLikeALiveAgent proves the one-off text path
// used by workflow generation goes through the same dispatch as a live
// agent call — a configured wrapper answers it exactly like it would answer
// agent(), so generation is provider-agnostic rather than codex-only.
func TestRunProviderTextDispatchesLikeALiveAgent(t *testing.T) {
	clearProviderEnv(t)
	tmp := t.TempDir()
	wrapperScript := filepath.Join(tmp, "fake-wrapper.sh")
	if err := os.WriteFile(wrapperScript, []byte(`#!/bin/sh
printf 'generated by wrapper' > "$PALLIUM_WORKFLOW_OUTPUT_FILE"
`), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PALLIUM_WORKFLOW_PROVIDER", "grok")
	t.Setenv("PALLIUM_WORKFLOW_PROVIDER_GROK_COMMAND", wrapperScript)

	r := &Runner{}
	out, err := r.RunProviderText(context.Background(), "write me a workflow")
	if err != nil {
		t.Fatal(err)
	}
	if out != "generated by wrapper" {
		t.Fatalf("RunProviderText = %q, want %q", out, "generated by wrapper")
	}
}

func TestRunProviderTextUsesCodexByDefault(t *testing.T) {
	clearProviderEnv(t)
	tmp := t.TempDir()
	fakeCodex := fakeCodexBinary(t, filepath.Join(tmp, "argv.log"), `generated by codex`)
	r := &Runner{CodexBinary: fakeCodex}
	out, err := r.RunProviderText(context.Background(), "write me a workflow")
	if err != nil {
		t.Fatal(err)
	}
	if out != "generated by codex" {
		t.Fatalf("RunProviderText = %q, want %q", out, "generated by codex")
	}
}
