package codeindex

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"testing"
	"time"

	"github.com/tszaks/pallium/internal/db"
)

func TestRunIndexesGoSymbolsAndImports(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.26.0\n",
		"internal/store/store.go": `package store

// Store holds the connection.
type Store struct{ name string }

// Open returns a Store.
func Open(name string) (*Store, error) { return &Store{name: name}, nil }

func (s *Store) Name() string { return s.name }

const DefaultName = "main"

func unexportedHelper() {}
`,
		"main.go": `package main

import "example.com/app/internal/store"

func main() {
	s, _ := store.Open("x")
	_ = s.Name()
}
`,
	})

	store, repoID := openIndexed(t, repo)
	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if result.Reparsed != 2 {
		t.Fatalf("expected 2 files reparsed, got %d (%+v)", result.Reparsed, result)
	}

	symbols, err := store.SymbolsInFile(repoID, "internal/store/store.go")
	if err != nil {
		t.Fatalf("symbols: %v", err)
	}
	byName := map[string]db.CodeSymbol{}
	for _, symbol := range symbols {
		byName[symbol.Name] = symbol
	}

	if got := byName["Store"]; got.Kind != "struct" || !got.Exported {
		t.Fatalf("Store should be an exported struct, got %+v", got)
	}
	if got := byName["Store"]; got.Doc != "Store holds the connection." {
		t.Fatalf("expected the doc comment on Store, got %q", got.Doc)
	}
	if got := byName["Open"]; got.Kind != "func" || got.Signature != "func Open(name string) (*Store, error)" {
		t.Fatalf("unexpected Open symbol: %+v", got)
	}
	if got := byName["Name"]; got.Kind != "method" || got.Receiver != "*Store" {
		t.Fatalf("Name should be a method on *Store, got %+v", got)
	}
	if got := byName["DefaultName"]; got.Kind != "const" {
		t.Fatalf("DefaultName should be a const, got %+v", got)
	}
	if got := byName["unexportedHelper"]; got.Exported {
		t.Fatal("unexportedHelper should not be marked exported")
	}

	imports, err := store.ImportsFrom(repoID, "main.go")
	if err != nil {
		t.Fatalf("imports: %v", err)
	}
	if len(imports) != 1 {
		t.Fatalf("expected one import, got %+v", imports)
	}
	// A Go import addresses a package, so the edge points at the directory.
	if imports[0].ToPath != "internal/store" || imports[0].External {
		t.Fatalf("expected a resolved in-repo package edge, got %+v", imports[0])
	}

	callers, err := store.PathsReferencing(repoID, "Open")
	if err != nil {
		t.Fatalf("callers: %v", err)
	}
	if len(callers) != 1 || callers[0] != "main.go" {
		t.Fatalf("expected main.go to reference Open, got %v", callers)
	}
}

func TestRunOnlyReparsesChangedFiles(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod":  "module example.com/app\n\ngo 1.26.0\n",
		"a.go":    "package main\n\nfunc A() {}\n",
		"b.go":    "package main\n\nfunc B() {}\n",
		"main.go": "package main\n\nfunc main() { A(); B() }\n",
	})

	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("first run: %v", err)
	}

	second, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if second.Reparsed != 0 || second.Unchanged != 3 {
		t.Fatalf("an unchanged repo should reparse nothing, got %+v", second)
	}

	write(t, filepath.Join(repo, "a.go"), "package main\n\nfunc A() {}\n\nfunc ANew() {}\n")
	third, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("third run: %v", err)
	}
	if third.Reparsed != 1 || third.Unchanged != 2 {
		t.Fatalf("only the edited file should reparse, got %+v", third)
	}

	symbols, err := store.SymbolsInFile(repoID, "a.go")
	if err != nil {
		t.Fatalf("symbols: %v", err)
	}
	if len(symbols) != 2 {
		t.Fatalf("expected the new symbol to land, got %+v", symbols)
	}
}

func TestRunDropsDeletedFiles(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod":  "module example.com/app\n\ngo 1.26.0\n",
		"gone.go": "package main\n\nfunc Gone() {}\n",
		"main.go": "package main\n\nfunc main() { Gone() }\n",
	})

	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("first run: %v", err)
	}

	if err := os.Remove(filepath.Join(repo, "gone.go")); err != nil {
		t.Fatalf("remove: %v", err)
	}
	git(t, repo, "add", "-A")

	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if result.Removed != 1 {
		t.Fatalf("expected the deleted file to be dropped, got %+v", result)
	}

	symbols, err := store.SymbolsInFile(repoID, "gone.go")
	if err != nil {
		t.Fatalf("symbols: %v", err)
	}
	if len(symbols) != 0 {
		t.Fatalf("stale symbols survived deletion: %+v", symbols)
	}
}

func TestRunSkipsGeneratedFiles(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod":         "module example.com/app\n\ngo 1.26.0\n",
		"generated.go":   "// Code generated by protoc. DO NOT EDIT.\n\npackage main\n\nfunc Generated() {}\n",
		"handwritten.go": "package main\n\nfunc Handwritten() {}\n",
	})

	store, repoID := openIndexed(t, repo)
	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if result.Reparsed != 1 || result.Skipped != 1 {
		t.Fatalf("expected the generated file to be skipped, got %+v", result)
	}

	matches, err := store.SymbolsNamed(repoID, "Generated")
	if err != nil {
		t.Fatalf("lookup: %v", err)
	}
	if len(matches) != 0 {
		t.Fatalf("generated symbols should stay out of the index, got %+v", matches)
	}
}

func TestRunIndexesTypeScriptPythonAndSwift(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"web/session.ts": "export interface Session { id: string }\n\nexport function openSession(): Session {\n  return { id: '1' }\n}\n",
		"web/app.ts":     "import { openSession } from './session'\n\nexport const app = () => openSession()\n",
		"api/helper.py":  "class Helper:\n    def run(self):\n        return 1\n\ndef helper():\n    return Helper()\n",
		"api/app.py":     "from .helper import helper\n\ndef app():\n    return helper()\n",
		"ios/View.swift": "import SwiftUI\n\nstruct ContentView: View {\n    var body: some View { Text(\"hi\") }\n}\n\nfinal class Model {\n    func load() {}\n}\n",
	})

	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run: %v", err)
	}

	assertSymbol(t, store, repoID, "web/session.ts", "openSession", "func")
	assertSymbol(t, store, repoID, "web/session.ts", "Session", "interface")
	assertSymbol(t, store, repoID, "api/helper.py", "Helper", "class")
	assertSymbol(t, store, repoID, "api/helper.py", "run", "method")
	assertSymbol(t, store, repoID, "ios/View.swift", "ContentView", "struct")
	assertSymbol(t, store, repoID, "ios/View.swift", "Model", "class")
	assertSymbol(t, store, repoID, "ios/View.swift", "load", "func")

	tsImports, err := store.ImportsFrom(repoID, "web/app.ts")
	if err != nil {
		t.Fatalf("ts imports: %v", err)
	}
	if len(tsImports) != 1 || tsImports[0].ToPath != "web/session.ts" {
		t.Fatalf("expected a resolved relative TS import, got %+v", tsImports)
	}

	pyImports, err := store.ImportsFrom(repoID, "api/app.py")
	if err != nil {
		t.Fatalf("py imports: %v", err)
	}
	if len(pyImports) != 1 || pyImports[0].ToPath != "api/helper.py" {
		t.Fatalf("expected a resolved relative Python import, got %+v", pyImports)
	}
}

func TestSearchSymbolsRanksNameMatchesFirst(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.26.0\n",
		"a.go": `package main

// ReconcileLedger settles the outstanding entries.
func ReconcileLedger() {}

// Unrelated mentions reconcile only in prose.
func Unrelated() {}
`,
	})

	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run: %v", err)
	}

	matches, err := store.SearchSymbols(repoID, "reconcile", 5)
	if err != nil {
		t.Fatalf("search: %v", err)
	}
	if len(matches) == 0 || matches[0].Name != "ReconcileLedger" {
		t.Fatalf("expected the name match ranked first, got %+v", matches)
	}
}

func assertSymbol(t *testing.T, store *db.Store, repoID int64, path, name, kind string) {
	t.Helper()
	symbols, err := store.SymbolsInFile(repoID, path)
	if err != nil {
		t.Fatalf("symbols for %s: %v", path, err)
	}
	for _, symbol := range symbols {
		if symbol.Name == name && symbol.Kind == kind {
			return
		}
	}
	t.Fatalf("expected %s %s in %s, got %+v", kind, name, path, symbols)
}

func openIndexed(t *testing.T, repo string) (*db.Store, int64) {
	t.Helper()
	store, err := db.OpenPath(repo, filepath.Join(t.TempDir(), "index.sqlite"))
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })

	record, err := store.UpsertRepo("main", "", time.Now().UTC())
	if err != nil {
		t.Fatalf("upsert repo: %v", err)
	}
	return store, record.ID
}

func newRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	repo := t.TempDir()
	git(t, repo, "init", "-b", "main")
	git(t, repo, "config", "user.name", "Test User")
	git(t, repo, "config", "user.email", "test@example.com")
	for path, content := range files {
		write(t, filepath.Join(repo, path), content)
	}
	git(t, repo, "add", "-A")
	git(t, repo, "commit", "-m", "init")
	return repo
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func git(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, output)
	}
}

// TestRunResolvesTypeScriptESMSpecifiers covers the NodeNext convention where
// the import names the compiled file and the source on disk is TypeScript.
// Found on a real 858-file repo whose api/ directory reported zero in-repo
// dependencies for exactly this reason.
func TestRunResolvesTypeScriptESMSpecifiers(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"server/auth.ts":   "export function authenticate() { return true }\n",
		"server/audit.mts": "export function audit() {}\n",
		"api/handler.ts": `import { authenticate } from "../server/auth.js";
import { audit } from "../server/audit.mjs";

export function handle() {
  audit();
  return authenticate();
}
`,
	})

	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run: %v", err)
	}

	imports, err := store.ImportsFrom(repoID, "api/handler.ts")
	if err != nil {
		t.Fatalf("imports: %v", err)
	}
	resolved := map[string]string{}
	for _, imp := range imports {
		resolved[imp.RawSpec] = imp.ToPath
	}
	if got := resolved["../server/auth.js"]; got != "server/auth.ts" {
		t.Fatalf("expected ../server/auth.js to resolve to server/auth.ts, got %q", got)
	}
	if got := resolved["../server/audit.mjs"]; got != "server/audit.mts" {
		t.Fatalf("expected ../server/audit.mjs to resolve to server/audit.mts, got %q", got)
	}
}

// TestRunReparsesWhenParserVersionChanges is the guard for the failure this
// found in practice: after improving a parser, every content hash still
// matched, so nothing reparsed and the index stayed as wrong as before.
func TestRunReparsesWhenParserVersionChanges(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.26.0\n",
		"a.go":   "package main\n\nfunc A() {}\n",
	})

	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("first run: %v", err)
	}

	// Simulate an index written by a Pallium with older parsers: same content
	// hash, stale parser tag.
	if _, err := store.DB().Exec(`UPDATE code_files SET parser = 'go/ast@0' WHERE repo_id = ?`, repoID); err != nil {
		t.Fatalf("age the parser tag: %v", err)
	}

	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if result.Reparsed != 1 || result.Unchanged != 0 {
		t.Fatalf("a stale parser tag must force a reparse, got %+v", result)
	}
}

func TestRunSkipsSymlinksEscapingRepo(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"main.go": "package main\nfunc Main() {}\n",
	})
	outside := filepath.Join(t.TempDir(), "secret.py")
	write(t, outside, `SECRET = "x"`+"\n")
	if err := os.Symlink(outside, filepath.Join(repo, "leak.py")); err != nil {
		t.Fatalf("symlink: %v", err)
	}
	git(t, repo, "add", "leak.py")
	store, repoID := openIndexed(t, repo)
	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if result.Skipped < 1 {
		t.Fatalf("escaping symlink was not skipped: %+v", result)
	}
	symbols, err := store.SymbolsInFile(repoID, "leak.py")
	if err != nil {
		t.Fatalf("symbols: %v", err)
	}
	if len(symbols) != 0 {
		t.Fatalf("escaping symlink leaked symbols: %+v", symbols)
	}
}

func TestRunSkipsFilesUnderEscapingSymlinkDir(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"main.go": "package main\nfunc Main() {}\n",
	})
	outside := t.TempDir()
	outsideFile := filepath.Join(outside, "file.go")
	write(t, outsideFile, "package outside\nfunc Secret() {}\n")
	if err := os.Symlink(outside, filepath.Join(repo, "pkg")); err != nil {
		t.Fatalf("symlink: %v", err)
	}
	hash := exec.Command("git", "hash-object", "-w", outsideFile)
	hash.Dir = repo
	blob, err := hash.Output()
	if err != nil {
		t.Fatalf("hash object: %v", err)
	}
	git(t, repo, "update-index", "--add", "--cacheinfo",
		"100644,"+strings.TrimSpace(string(blob))+",pkg/file.go")

	store, repoID := openIndexed(t, repo)
	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if result.Skipped < 1 {
		t.Fatalf("file under escaping symlink directory was not skipped: %+v", result)
	}
	symbols, err := store.SymbolsInFile(repoID, "pkg/file.go")
	if err != nil {
		t.Fatalf("symbols: %v", err)
	}
	if len(symbols) != 0 {
		t.Fatalf("escaping symlink directory leaked symbols: %+v", symbols)
	}
}

func TestVendorishKeepsNestedOutputNames(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"internal/build/runner.go": "package runner\nfunc Run() {}\n",
		"src/out/encoder.ts":       "export function Encode() {}\n",
		"pkg/dist/types.go":        "package dist\nfunc Type() {}\n",
		"dist/bundle.js":           "function bundle() {}\n",
		"build/x.go":               "package build\nfunc X() {}\n",
		"foo/node_modules/x.js":    "function x() {}\n",
	})
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run: %v", err)
	}
	paths, err := store.CodeIndexedPaths(repoID)
	if err != nil {
		t.Fatalf("paths: %v", err)
	}
	got := map[string]bool{}
	for _, path := range paths {
		got[path] = true
	}
	for _, path := range []string{"internal/build/runner.go", "src/out/encoder.ts", "pkg/dist/types.go"} {
		if !got[path] {
			t.Fatalf("nested source output path was excluded: %s", path)
		}
	}
	for _, path := range []string{"dist/bundle.js", "build/x.go", "foo/node_modules/x.js"} {
		if got[path] {
			t.Fatalf("vendorish path was indexed: %s", path)
		}
	}
}

func TestRunReparsesWhenResolverInputsChange(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.26.0\n",
		"a.go":   "package main\nimport _ \"example.com/app/lib\"\nfunc A() {}\n",
	})
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("first run: %v", err)
	}
	imports, err := store.ImportsFrom(repoID, "a.go")
	if err != nil || len(imports) != 1 || imports[0].External || imports[0].ToPath != "" {
		t.Fatalf("missing local package should remain non-external: %+v err=%v", imports, err)
	}
	write(t, filepath.Join(repo, "lib", "lib.go"), "package lib\nfunc L() {}\n")
	git(t, repo, "add", "-A")
	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if result.Reparsed == 0 {
		t.Fatalf("resolver input change did not reparse files: %+v", result)
	}
	imports, err = store.ImportsFrom(repoID, "a.go")
	if err != nil || len(imports) != 1 || imports[0].External || imports[0].ToPath != "lib" {
		t.Fatalf("new package was not resolved: %+v err=%v", imports, err)
	}
}

func TestNestedGoModulesStayExternal(t *testing.T) {
	for name, requireLine := range map[string]string{
		"block":  "require (\n\texample.com/lib/v2 v2.0.0\n)",
		"single": "require example.com/lib/v2 v2.0.0",
	} {
		t.Run(name, func(t *testing.T) {
			repo := newRepo(t, map[string]string{
				"go.mod": "module example.com/lib\n\ngo 1.26.0\n\n" + requireLine + "\n",
				"main.go": `package main

import (
	_ "example.com/lib/v2/foo"
	_ "example.com/lib/internal/missing"
)

func Main() {}
`,
			})
			store, repoID := openIndexed(t, repo)
			if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
				t.Fatalf("run: %v", err)
			}
			imports, err := store.ImportsFrom(repoID, "main.go")
			if err != nil {
				t.Fatalf("imports: %v", err)
			}
			bySpec := map[string]db.CodeImport{}
			for _, item := range imports {
				bySpec[item.RawSpec] = item
			}
			if item := bySpec["example.com/lib/v2/foo"]; !item.External || item.ToPath != "" {
				t.Fatalf("nested module import should stay external: %+v", item)
			}
			if item := bySpec["example.com/lib/internal/missing"]; item.External || item.ToPath != "" {
				t.Fatalf("unresolved in-module import should stay local: %+v", item)
			}
		})
	}
	t.Run("ancestor requirement", func(t *testing.T) {
		repo := newRepo(t, map[string]string{
			"go.mod": "module example.com/lib/v2\n\ngo 1.26.0\n\nrequire example.com/lib v1.0.0\n",
			"main.go": `package main

import (
	_ "example.com/lib/v2/internal/missing"
	_ "example.com/lib/foo"
)

func Main() {}
`,
		})
		store, repoID := openIndexed(t, repo)
		if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
			t.Fatalf("run: %v", err)
		}
		imports, err := store.ImportsFrom(repoID, "main.go")
		if err != nil {
			t.Fatalf("imports: %v", err)
		}
		bySpec := map[string]db.CodeImport{}
		for _, item := range imports {
			bySpec[item.RawSpec] = item
		}
		if item := bySpec["example.com/lib/v2/internal/missing"]; item.External || item.ToPath != "" {
			t.Fatalf("current nested module import should stay local: %+v", item)
		}
		if item := bySpec["example.com/lib/foo"]; !item.External || item.ToPath != "" {
			t.Fatalf("outside current module import should stay external: %+v", item)
		}
	})
}

func TestResolverKeyIgnoresMissingTrackedConfigs(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"tsconfig.json": `{"compilerOptions":{"baseUrl":"."}}`,
		"src/main.ts":   "export function Main() {}\n",
	})
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("first run: %v", err)
	}
	if err := os.Remove(filepath.Join(repo, "tsconfig.json")); err != nil {
		t.Fatalf("remove config: %v", err)
	}
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run with missing tracked config: %v", err)
	}
}

func TestUnindexedCandidatesSkipsUnparseableFiles(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"main.go": "package main\nfunc Main() {}\n",
	})
	write(t, filepath.Join(repo, "bad.go"), "")
	write(t, filepath.Join(repo, "ok.go"), "package main\nfunc OK() {}\n")
	git(t, repo, "add", "bad.go", "ok.go")
	candidates, err := UnindexedCandidates(repo, map[string]struct{}{"main.go": {}})
	if err != nil {
		t.Fatalf("candidates: %v", err)
	}
	if len(candidates) != 1 || candidates[0] != "ok.go" {
		t.Fatalf("unexpected unindexed candidates: %v", candidates)
	}
}

func TestResolverKeyTracksUntrackedConfigs(t *testing.T) {
	t.Run("root config", func(t *testing.T) {
		repo := newRepo(t, map[string]string{
			"src/a.ts": "export const value = 1\n",
		})
		paths := []string{"src/a.ts"}
		first, err := resolverKey(repo, paths)
		if err != nil {
			t.Fatalf("first key: %v", err)
		}
		write(t, filepath.Join(repo, "tsconfig.json"), `{"compilerOptions":{"paths":{"@/*":["src/*"]}}}`)
		second, err := resolverKey(repo, paths)
		if err != nil {
			t.Fatalf("second key: %v", err)
		}
		if first == second {
			t.Fatal("creating an untracked resolver config did not change the key")
		}
		write(t, filepath.Join(repo, "tsconfig.json"), `{"compilerOptions":{"paths":{"@/*":["other/*"]}}}`)
		third, err := resolverKey(repo, paths)
		if err != nil {
			t.Fatalf("third key: %v", err)
		}
		if second == third {
			t.Fatal("editing an untracked resolver config did not change the key")
		}
	})
	t.Run("untracked extends parent", func(t *testing.T) {
		repo := newRepo(t, map[string]string{
			"src/a.ts": "export const value = 1\n",
		})
		write(t, filepath.Join(repo, "tsconfig.json"), `{"extends":"./base.json"}`)
		write(t, filepath.Join(repo, "base.json"), `{"compilerOptions":{"baseUrl":"src"}}`)
		paths := []string{"src/a.ts"}
		first, err := resolverKey(repo, paths)
		if err != nil {
			t.Fatalf("first key: %v", err)
		}
		write(t, filepath.Join(repo, "base.json"), `{"compilerOptions":{"baseUrl":"other"}}`)
		second, err := resolverKey(repo, paths)
		if err != nil {
			t.Fatalf("second key: %v", err)
		}
		if first == second {
			t.Fatal("editing an untracked extends parent did not change the key")
		}
	})
}

func TestRunReparsesWhenUntrackedTSConfigChanges(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"src/a.ts": "export const value = 1\n",
	})
	write(t, filepath.Join(repo, "tsconfig.json"), `{"compilerOptions":{"paths":{"@/*":["src/*"]}}}`)
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("first run: %v", err)
	}
	write(t, filepath.Join(repo, "tsconfig.json"), `{"compilerOptions":{"paths":{"@/*":["other/*"]}}}`)
	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if result.Reparsed == 0 {
		t.Fatalf("untracked resolver config change did not reparse: %+v", result)
	}
}

func TestResolverInputsRejectSpecialFiles(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"src/a.ts": "import value from '@/value'\nexport const result = value\n",
	})
	outside := t.TempDir()
	outsideConfig := filepath.Join(outside, "tsconfig.json")
	write(t, outsideConfig, `{"compilerOptions":{"paths":{"@/*":["outside/*"]}}}`)
	if err := os.Symlink(outsideConfig, filepath.Join(repo, "tsconfig.json")); err != nil {
		t.Fatalf("tsconfig symlink: %v", err)
	}
	if err := syscall.Mkfifo(filepath.Join(repo, "jsconfig.json"), 0o600); err != nil {
		t.Logf("skipping FIFO subcase: %v", err)
	} else {
		if _, _, ok := readContained(repo, "jsconfig.json"); ok {
			t.Fatal("FIFO resolver config was readable")
		}
	}
	write(t, filepath.Join(outside, "go.mod"), "module outside.example/app\n")
	if err := os.Symlink(filepath.Join(outside, "go.mod"), filepath.Join(repo, "go.mod")); err != nil {
		t.Fatalf("go.mod symlink: %v", err)
	}
	if _, _, ok := readContained(repo, "go.mod"); ok {
		t.Fatal("outside go.mod symlink was readable")
	}
	if _, err := resolverKey(repo, []string{"src/a.ts"}); err != nil {
		t.Fatalf("resolver key followed a rejected input: %v", err)
	}
	resolver := NewResolver(repo, []string{"src/a.ts"})
	parsed, ok := Parse("src/a.ts", []byte("import value from '@/value'\nexport const result = value\n"), resolver)
	if !ok {
		t.Fatal("TypeScript fixture was not parsed")
	}
	for _, imp := range parsed.Imports {
		if imp.ToPath != "" {
			t.Fatalf("resolver followed a rejected config: %+v", imp)
		}
	}
}

func TestUnresolvedTSAliasImportsStayLocal(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"tsconfig.json": `{"compilerOptions":{"paths":{"@/*":["src/*"]}}}`,
		"src/a.ts":      "import missing from '@/missing'\nimport react from 'react'\nexport const value = missing || react\n",
	})
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run: %v", err)
	}
	imports, err := store.ImportsFrom(repoID, "src/a.ts")
	if err != nil {
		t.Fatalf("imports: %v", err)
	}
	bySpec := map[string]db.CodeImport{}
	for _, item := range imports {
		bySpec[item.RawSpec] = item
	}
	if item := bySpec["@/missing"]; item.External || item.ToPath != "" {
		t.Fatalf("unresolved TS alias should stay local: %+v", item)
	}
	if item := bySpec["react"]; !item.External || item.ToPath != "" {
		t.Fatalf("package import should stay external: %+v", item)
	}
}

func TestUnresolvedRelativeImportsStayLocal(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"app.js": "import missing from './missing'; import react from 'react';\nexport function App() { return missing || react }\n",
		"app.py": "from .missing import x\n\ndef app():\n    return x\n",
	})
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run: %v", err)
	}
	js, err := store.ImportsFrom(repoID, "app.js")
	if err != nil {
		t.Fatalf("js imports: %v", err)
	}
	bySpec := map[string]db.CodeImport{}
	for _, item := range js {
		bySpec[item.RawSpec] = item
	}
	if bySpec["./missing"].External || bySpec["./missing"].ToPath != "" || !bySpec["react"].External {
		t.Fatalf("unexpected JS import classification: %+v", bySpec)
	}
	py, err := store.ImportsFrom(repoID, "app.py")
	if err != nil {
		t.Fatalf("py imports: %v", err)
	}
	if len(py) != 1 || py[0].External || py[0].ToPath != "" {
		t.Fatalf("unexpected Python import classification: %+v", py)
	}
}

func TestTSAliasOrderIsDeterministic(t *testing.T) {
	aliases := TSConfigAliases{Paths: map[string][]string{
		"@/*":         {"src/*"},
		"@/special/*": {"special/*"},
	}}
	for iteration := 0; iteration < 20; iteration++ {
		bases := resolveTSAliasBases("@/special/thing", aliases)
		if len(bases) == 0 || bases[0] != "special/thing" {
			t.Fatalf("specific alias did not win on iteration %d: %v", iteration, bases)
		}
	}
}

func TestGoRefsRecordGenericCalls(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.26.0\n",
		"defs.go": `package main
func Transform[T any](v T) T { return v }
func Combine[A any, B any](a A) B { var b B; return b }
`,
		"main.go": `package main
func main() {
	Transform[string]("x")
	Combine[int, string](1)
}
`,
	})
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("run: %v", err)
	}
	for _, name := range []string{"Transform", "Combine"} {
		callers, err := store.PathsReferencing(repoID, name)
		if err != nil {
			t.Fatalf("refs %s: %v", name, err)
		}
		if len(callers) != 1 || callers[0] != "main.go" {
			t.Fatalf("generic call %s was not indexed: %v", name, callers)
		}
	}
}

func TestRunReportsTotalCounts(t *testing.T) {
	repo := newRepo(t, map[string]string{
		"go.mod":  "module example.com/app\n\ngo 1.26.0\n",
		"main.go": "package main\nfunc Main() {}\n",
	})
	store, repoID := openIndexed(t, repo)
	if _, err := Run(store, repoID, time.Now().UTC()); err != nil {
		t.Fatalf("first run: %v", err)
	}
	result, err := Run(store, repoID, time.Now().UTC())
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if result.Unchanged == 0 || result.Symbols == 0 {
		t.Fatalf("second run lost total counts: %+v", result)
	}
}
