package codeindex

import (
	"path/filepath"
	"strings"
)

// Lang is the language label stored on every indexed file. It drives which
// parser runs and is a useful filter on its own ("what Swift is in here").
func Lang(path string) string {
	switch strings.ToLower(filepath.Ext(path)) {
	case ".go":
		return "go"
	case ".ts", ".mts", ".cts":
		return "typescript"
	case ".tsx":
		return "tsx"
	case ".js", ".mjs", ".cjs":
		return "javascript"
	case ".jsx":
		return "jsx"
	case ".py":
		return "python"
	case ".swift":
		return "swift"
	case ".rb":
		return "ruby"
	case ".rs":
		return "rust"
	case ".java":
		return "java"
	case ".kt", ".kts":
		return "kotlin"
	case ".c", ".h":
		return "c"
	case ".cc", ".cpp", ".hpp", ".cxx":
		return "cpp"
	case ".m", ".mm":
		return "objc"
	case ".cs":
		return "csharp"
	case ".php":
		return "php"
	case ".sh", ".bash", ".zsh":
		return "shell"
	case ".sql":
		return "sql"
	case ".md", ".mdx":
		return "markdown"
	case ".json":
		return "json"
	case ".yml", ".yaml":
		return "yaml"
	case ".toml":
		return "toml"
	case ".html":
		return "html"
	case ".css", ".scss", ".sass":
		return "css"
	default:
		return ""
	}
}

// Parseable reports whether a language has a symbol parser. Files outside this
// set are skipped entirely rather than stored with zero symbols: a lockfile or
// a 3MB JSON fixture in the index is noise that makes every later query worse.
func Parseable(lang string) bool {
	switch lang {
	case "go", "typescript", "tsx", "javascript", "jsx", "python", "swift",
		"ruby", "rust", "java", "kotlin", "csharp", "php", "c", "cpp", "objc":
		return true
	default:
		return false
	}
}

// generatedMarkers are the banners code generators leave at the top of their
// output. A generated file's symbols are real, but they are not knowledge a
// human wrote, and letting 40,000 of them into the symbol table drowns the
// ones that matter.
var generatedMarkers = []string{
	"// Code generated by",
	"// @generated",
	"/* @generated",
	"# @generated",
	"# Code generated by",
	"// AUTOGENERATED",
	"// DO NOT EDIT",
	"<auto-generated",
}

func looksGenerated(content []byte) bool {
	head := content
	if len(head) > 2048 {
		head = head[:2048]
	}
	text := string(head)
	for _, marker := range generatedMarkers {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}

// vendorishAnywhere are directories whose contents are someone else's code even
// when they are committed. git ls-files already drops what .gitignore
// excludes; this catches repos that commit dependencies.
var vendorishAnywhere = []string{
	"vendor/",
	"node_modules/",
	"third_party/",
	"Pods/",
	".build/",
	"coverage/",
	".next/",
	"__pycache__/",
}

// outputRootsOnly matches generated output directories only at the repository
// root; nested names are often real source.
var outputRootsOnly = []string{"dist/", "build/", "out/"}

func vendorish(path string) bool {
	for _, prefix := range vendorishAnywhere {
		if strings.HasPrefix(path, prefix) || strings.Contains(path, "/"+prefix) {
			return true
		}
	}
	for _, prefix := range outputRootsOnly {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}
	return false
}
